<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VTIPL-H-PC249-L" failures="2" tests="8" name="Sanity" time="32.296" errors="0" timestamp="2024-06-25T20:08:45 IST">
  <testcase classname="testNGDemo.TestNGDemo" name="test1Class1" time="0.024"/>
  <testcase classname="testNGDemo.TestNGDemo" name="test2Class1" time="0.003"/>
  <testcase classname="testNGDemo.TestNGDemo" name="test3Class1" time="0.014">
    <failure type="java.lang.AssertionError" message="Failed demo case expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed demo case expected [true] but found [false]
at testNGDemo.TestNGDemo.test3Class1(TestNGDemo.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3Class1 -->
  <testcase classname="testNGDemo.TestngDemo1" name="testcaseOneClass1" time="0.004"/>
  <testcase classname="testNGDemo.TestngDemo1" name="testcaseTwoClass2" time="0.008"/>
  <testcase classname="testNGDemo.TestngDemo2" name="testcaseOneClass1" time="0.006"/>
  <testcase classname="testNGDemo.TestngDemo2" name="testcaseTwoClass2" time="0.005"/>
  <testcase classname="com.mycompany.selenium.DemoQATest1" name="fillTheForm" time="2.252">
    <failure type="java.lang.AssertionError" message="failed case Demo expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: failed case Demo expected [true] but found [false]
at com.mycompany.selenium.DemoQATest1.fillTheForm(DemoQATest1.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- fillTheForm -->
</testsuite> <!-- Sanity -->
