<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VTIPL-H-PC249-L" failures="1" tests="7" name="Sanity" time="0.317" errors="0" timestamp="2024-07-02T12:49:43 IST">
  <testcase classname="testNGDemo.TestNGDemo" name="test1Class1" time="0.017"/>
  <testcase classname="testNGDemo.TestNGDemo" name="test2Class1" time="0.002"/>
  <testcase classname="testNGDemo.TestNGDemo" name="test3Class1" time="0.005">
    <failure type="java.lang.AssertionError" message="Verification of the status expected [Accepted] but found [Completed]">
      <![CDATA[java.lang.AssertionError: Verification of the status expected [Accepted] but found [Completed]
at testNGDemo.TestNGDemo.test3Class1(TestNGDemo.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3Class1 -->
  <testcase classname="testNGDemo.TestngDemo1" name="testcaseOneClass1" time="0.003"/>
  <testcase classname="testNGDemo.TestngDemo1" name="testcaseTwoClass2" time="0.002"/>
  <testcase classname="testNGDemo.TestngDemo2" name="testcaseOneClass1" time="0.003"/>
  <testcase classname="testNGDemo.TestngDemo2" name="testcaseTwoClass2" time="0.002"/>
</testsuite> <!-- Sanity -->
